# Global settings for build
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  base = "/"

# Environment variables
[build.environment]
  NODE_VERSION = "18.20.3"
  NPM_VERSION = "9.8.1"
  NODE_ENV = "production"
  VITE_APP_VERSION = "1.0.0"
  NPM_FLAGS = "--legacy-peer-deps"

# Development settings
[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"
  targetPort = 3000
  framework = "vite"

# Redirects and proxies
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy for local development
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.google-analytics.com;"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Enable form detection
[forms]
  # This enables Netlify's built-in form detection
  # No additional configuration needed for basic form handling

# Function settings
[functions]
  # Set the Node.js version for Netlify Functions
  node_bundler = "esbuild"
  external_node_modules = ["google-spreadsheet", "google-auth-library"]

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.google-analytics.com;"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
