# Global settings for build
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Environment variables
[build.environment]
  NODE_VERSION = "18.20.3"
  NODE_ENV = "production"
  VITE_APP_VERSION = "1.0.0"

# SPA Fallback - handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
