# Global settings for build
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Environment variables
[build.environment]
  NODE_VERSION = "18.20.3"
  NPM_VERSION = "9.8.1"
  NODE_ENV = "production"
  VITE_APP_VERSION = "1.0.0"
  NPM_FLAGS = "--legacy-peer-deps"

# Form submission handling
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Handle form submissions
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"
  targetPort = 3000
  framework = "vite"

# SPA Fallback - handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.google-analytics.com;"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
