# Global settings for build
[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  functions = "netlify/functions"
  base = "/"

# Environment variables
[build.environment]
  NODE_VERSION = "18.20.3"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"
  CI = "false"
  VITE_APP_VERSION = "1.0.0"
  NETLIFY_USE_YARN = "false"
  NPM_VERBOSE = "true"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

# Development settings
[dev]
  framework = "vite"
  command = "npm run dev"
  port = 8888  # Port for the Netlify proxy
  targetPort = 3000  # Port where Vite runs
  publish = "dist"
  autoLaunch = true

[dev.lifecycle]
  onStart = "npm run dev"

# Build settings
[build.processing]
  skip_processing = false

# Image optimization
[build.processing.html]
  pretty_urls = true

# Build plugins
[[plugins]]
  package = "@netlify/plugin-sitemap"

# SPA Fallback - handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
