# Global settings
[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"
  base = "/"

# Environment variables
[build.environment]
  NODE_VERSION = "18.20.3"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"
  CI = "false"
  VITE_APP_VERSION = "1.0.0"
  NETLIFY_USE_YARN = "false"

# Development settings
[dev]
  framework = "vite"
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  publish = "dist"
  autoLaunch = true

# Build settings
[build.processing]
  skip_processing = false

# Image optimization
[build.processing.html]
  pretty_urls = true

# Build plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
[[plugins]]
  package = "@netlify/plugin-sitemap"
  
# Context-specific settings
[context.production]
  command = "npm run build"
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "staging" }

[context.branch-deploy]
  environment = { NODE_ENV = "staging" }

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/functions"]

# SPA Fallback - handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# API Proxy
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:;"

# Cache Control for Assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:;"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"
  targetPort = 3000

[dev.lifecycle]
  onStart = "npm run dev"
